#Global Default Properties Configuration
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 50

resilience4j.timelimiter:
    configs:
        default:
            timeoutDuration: 5s
            cancelRunningFuture: true
            
            
            
#Configs Properties Configuration
#resilience4j.circuitbreaker:
#    configs:
#        groupA:
#            registerHealthIndicator: true
#            slidingWindowSize: 200
#
#resilience4j.timelimiter:
#    configs:
#        groupC:
#            timeoutDuration: 3s
#            cancelRunningFuture: true            
            

#Instances Properties Configuration
#resilience4j.circuitbreaker:
# instances:
#     backendA:
#         registerHealthIndicator: true
#         slidingWindowSize: 100
#     backendB:
#         registerHealthIndicator: true
#         slidingWindowSize: 10
#         permittedNumberOfCallsInHalfOpenState: 3
#         slidingWindowType: TIME_BASED
#         recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
#
#resilience4j.timelimiter:
# instances:
#     backendA:
#         timeoutDuration: 2s
#         cancelRunningFuture: true
#     backendB:
#         timeoutDuration: 1s
#         cancelRunningFuture: false

resilience4j.thread-pool-bulkhead:
    instances:
        backendA:
            maxThreadPoolSize: 1
            coreThreadPoolSize: 1
resilience4j.bulkhead:
    instances:
        backendB:
            maxConcurrentCalls: 10